[package]
edition = "2018"
name = "zerocopy-derive"
version = "0.3.1"
authors = ["Joshua Liebow-Feeser <joshlf@google.com>"]
description = "Custom derive for traits from the zerocopy crate"
# license-file = "../../../../LICENSE"
# repository = "https://fuchsia.googlesource.com/fuchsia/+/HEAD/src/lib/zerocopy/zerocopy-derive"

include = ["src/*", "tests/*", "Cargo.toml"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.1"
quote = "1.0.10"
syn = { version = "1.0.5", features = ["visit"] }

[dev-dependencies]
zerocopy = { path = "../" }
compiletest_rs = "0.7"
